analytics: {}
color:
  brandColors:
    - '#FEFEFE'
    - '#7BA6D0'
    - '#99BED9'
    - '#B5D1E6'
    - '#4C716A'
  brandStrength: 0.961149
  lightness: 0.735442
  rhythmicContrast: 0.763324
  saturation: 0.252871
cta: {}
layout_spectrum: 0.764358
name: lftest
opengraph: {}
purpose: {}
typography_spectrum: 0.766892
